### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by frenky-strasak** [nixingyang/FlipReID#1]
Hi,
I followed your [environment installation guide](https://github.com/nixingyang/FlipReID#environment) and when I run following command:

`python -u solution.py --dataset_name "Market1501" --backbone_model_name "resnet50" --pretrained_model_file_path models/Market1501_resnesta50_18209984.h5 --use_horizontal_flipping_inside_model --use_horizontal_flipping_in_evaluation --output_folder_path "evaluation_only" --evaluation_only --freeze_backbone_for_N_epochs 0 --testing_size 1.0 --evaluate_testing_every_N_epochs 1 --use_re_ranking
`

it throws:

`Visualizing training_model_140079423991184 ...
Visualizing inference_model_140083017889056 ...
Visualizing preprocess_input_140083002997872 ...
Visualizing features_init_block_140083019205408 ...
Visualizing features_stage1_140083019021856 ...
Visualizing features_stage2_140083015402016 ...
Visualizing features_stage3_140083026762240 ...
Visualizing features_stage4_regional_branch_140081261253392 ...
Visualizing features_stage4_global_branch_140081365706064 ...
Visualizing classification_model_140080432377376 ...
Initiating the image augmentor ...
Perform training ...
Loading weights from models/Market1501_resnesta50_18209984.h5 ...
Traceback (most recent call last):
  File "solution.py", line 925, in <module>
    app.run(main)
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "solution.py", line 852, in main
    training_model.load_weights(pretrained_model_file_path)
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 1266, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 696, in load_weights_from_hdf5_group
    weight_values = preprocess_weights_for_loading(
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 320, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 297, in convert_nested_model
    preprocessed = preprocess_weights_for_loading(
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 402, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 5, in transpose
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 651, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/frenky/anaconda3/envs/tf2.2/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array`

Do you have any hint? Thank you.

----------------------
os: ubuntu 18.04
gpu: rtx 3090 24Gb
tensoflow: 2.2.2

**Comment by nixingyang** [comment]
Hi,
Please try `--backbone_model_name "resnesta50"`. As a side note, you've got a nice GPU :-)
All the best.
Xingyang

**Comment by frenky-strasak** [comment]
My bad. Thank you!

**Comment by FatemehAnvari** [comment]
i tried whit 
!python3 -u solution.py --dataset_name "Market1501" --backbone_model_name "resnesta50" --pretrained_model_file_path "/content/FlipReID/models/resnesta50-0439-9ef477b8.tf2.h5" --use_horizontal_flipping_inside_model --use_horizontal_flipping_in_evaluation --output_folder_path "evaluation_only" --evaluation_only --freeze_backbone_for_N_epochs 0 --testing_size 1.0 --evaluate_testing_every_N_epochs 1


but get this error:

Initiating the image augmentor ...
Perform training ...
pretrained_model_file_path:/content/FlipReID/models/resnesta50-0439-9ef477b8.tf2.h5
len(pretrained_model_file_path):56
Loading weights from /content/FlipReID/models/resnesta50-0439-9ef477b8.tf2.h5 ...
Traceback (most recent call last):
  File "/content/FlipReID/solution.py", line 928, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/FlipReID/solution.py", line 855, in main
    training_model.load_weights(pretrained_model_file_path)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 655, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array

**Comment by nixingyang** [comment]
@FatemehAnvari This could be, again, an issue related to the version of TensorFlow. Are you using TensorFlow 2.2.3?
